# Generated by Django 5.1.3 on 2024-11-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chatbot", "0002_delete_appointment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("specialization", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("contact_number", models.CharField(max_length=15)),
                ("available_days", models.CharField(max_length=50)),
                ("available_time", models.CharField(max_length=20)),
            ],
        ),
    ]
