# Generated by Django 5.1.3 on 2024-11-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
