# Generated by Django 5.1.3 on 2024-11-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0004_doctor_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="url",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
